/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sz_blemed_myapplication_MainActivity */

#ifndef _Included_com_sz_blemed_myapplication_MainActivity
#define _Included_com_sz_blemed_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sz_blemed_myapplication_MainActivity
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sz_blemed_myapplication_MainActivity_helloJni
  (JNIEnv *, jclass);

/*
 * Class:     com_sz_blemed_myapplication_MainActivity
 * Method:    addCalc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sz_blemed_myapplication_MainActivity_addCalc
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
